package fr.cop1.studentpantrybackend.enums;

public enum NotificationType {
    RESERVATION_CONFIRMATION,
    RESERVATION_REMINDER,
    RESERVATION_CANCELLATION,
    VOLUNTEER_CONFIRMATION,
    VOLUNTEER_REMINDER,
    WAITLIST_AVAILABLE,
    ACCOUNT_APPROVED,
    ACCOUNT_REJECTED,
    SYSTEM_NOTIFICATION
}
